#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomRowView.Resource", IsApplication=true)]

namespace CustomRowView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::CustomRowView.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::CustomRowView.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::CustomRowView.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::CustomRowView.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::CustomRowView.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::CustomRowView.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::CustomRowView.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::CustomRowView.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::CustomRowView.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::CustomRowView.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::CustomRowView.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::CustomRowView.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::CustomRowView.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::CustomRowView.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::CustomRowView.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::CustomRowView.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::CustomRowView.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::CustomRowView.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::CustomRowView.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::CustomRowView.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::CustomRowView.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::CustomRowView.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::CustomRowView.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::CustomRowView.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::CustomRowView.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::CustomRowView.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::CustomRowView.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::CustomRowView.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::CustomRowView.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::CustomRowView.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::CustomRowView.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::CustomRowView.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::CustomRowView.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::CustomRowView.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::CustomRowView.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::CustomRowView.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::CustomRowView.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int books = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bulbs = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int clouds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CustomSelector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int FlowerBuds = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Fruits = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_errorstatus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_successstatus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lambo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int laptop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Legumes = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int monoandroidsplash = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pc = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int roundedbg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int roundedbgdark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Tubers = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Vegetables = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int Image = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int List = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int Rent = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int Text = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Text1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Text2 = 2131165186;
			
			// aapt resource value: 0x7f070011
			public const int adText = 2131165201;
			
			// aapt resource value: 0x7f070005
			public const int banner = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int details = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int digitalClock1 = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int imageView1 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int itemdesc = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int loadingImage = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int loadingProgressBar = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int loadingProgressWheel = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int login = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int newad = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int rentdetails = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int submitad = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int textClock1 = 2131165194;
			
			// aapt resource value: 0x7f070014
			public const int textViewStatus = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int uname = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int upass = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int detailviews = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout1 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout3 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loading = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingprogress = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
